- name: Selenium
  hosts: host
  become: true
  connection: local
  tasks:
    - name: Copy file with owner and permission, using symbolic representation
      copy:
        src: ./insure_selenium.jar
        dest: /home/ubuntu/insure_selenium.jar
        owner: jenkins
        group: jenkins
        mode: u=rwx,g=r,o=r
    - name: run selenium jar
      command: java -jar /home/ubuntu/insure_selenium.jar
      become: yes
      become_user: jenkins
